### ISSUE TITLE
Old version on packagist.org

### ISSUE THREAD

**Issue by lars85** [axovis/Axovis.Neos.LanguageDetection#6]
https://packagist.org/packages/axovis/languagedetection lists 1.0.12 as newest version instead of 3.0.0.

I guess this is because of the namespace change (https://github.com/axovis/Axovis.Neos.LanguageDetection/commit/85dda7830ae05cc75fefecfc7e324d00756aef91).

**Comment by coders-market** [comment]
Thank you for reporting. Issue is fixed

**Comment by ghost** [comment]
Issue fixed
